name: Hello World

on: workflow_dispatch

jobs:
  hello_world:
    runs-on: codebuild-cb-selfhosted-runners-action-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Hello World
        run: echo "Hello World"